//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klient.v03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delivery_Details
    {
        public int Id { get; set; }
        public int Id_dostawy { get; set; }
        public int Id_produktu { get; set; }
        public double Netto { get; set; }
        public int Sztuk { get; set; }
    
        public virtual Deliveries Deliveries { get; set; }
        public virtual Products Products { get; set; }
    }
}
