//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klient.v03
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliveryDetail
    {
        public int Id { get; set; }
        public int DostawaId { get; set; }
        public int ProduktId { get; set; }
        public double Netto { get; set; }
        public int Sztuk { get; set; }
        public int Vat { get; set; }
    
        public virtual Delivery Delivery { get; set; }
        public virtual Product Product { get; set; }
    }
}
