//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klient.v03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.Order_Details = new HashSet<Order_Details>();
        }
    
        public int Zamowienie_id { get; set; }
        public System.DateTime Data_zamowienia { get; set; }
        public int Id_klienta { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual ICollection<Order_Details> Order_Details { get; set; }
    }
}
