//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klient.v03
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int ZamowienieId { get; set; }
        public int ProduktId { get; set; }
        public int Ilosc { get; set; }
        public string MiastoDostawy { get; set; }
        public string AdresDostawy { get; set; }
        public string KodPocztowyDostawy { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }

        public Order Order1
        {
            get
            {
                throw new System.NotImplementedException();
            }
            set
            {
            }
        }

        public ShopContext ShopContext
        {
            get
            {
                throw new System.NotImplementedException();
            }
            set
            {
            }
        }
    }
}
