//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klient.v03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Price
    {
        public int CenaId { get; set; }
        public int ProduktId { get; set; }
        public System.DateTime Od { get; set; }
        public Nullable<System.DateTime> Do { get; set; }
        public double Cena { get; set; }

        public virtual Product Product { get; set; }

        public Product Product1
        {
            get
            {
                throw new System.NotImplementedException();
            }
            set
            {
            }
        }

        public ShopContext ShopContext
        {
            get
            {
                throw new System.NotImplementedException();
            }
            set
            {
            }
        }

        public EditingWindow EditingWindow
        {
            get
            {
                throw new System.NotImplementedException();
            }
            set
            {
            }
        }
    }
}
