//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klient.v03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.DeliveryDetail = new HashSet<DeliveryDetail>();
            this.OrderDetail = new HashSet<OrderDetail>();
            this.Price = new HashSet<Price>();
            this.Vat = new HashSet<Vat>();
        }
    
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public int KategoriaId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<DeliveryDetail> DeliveryDetail { get; set; }
        public virtual ICollection<OrderDetail> OrderDetail { get; set; }
        public virtual ICollection<Price> Price { get; set; }
        public virtual Store Store { get; set; }
        public virtual ICollection<Vat> Vat { get; set; }
    }
}
