//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klient.v03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Delivery_Details = new HashSet<Delivery_Details>();
            this.Order_Details = new HashSet<Order_Details>();
            this.Prices = new HashSet<Prices>();
            this.Vat = new HashSet<Vat>();
        }
    
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public int Kategoria_id { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Delivery_Details> Delivery_Details { get; set; }
        public virtual ICollection<Order_Details> Order_Details { get; set; }
        public virtual ICollection<Prices> Prices { get; set; }
        public virtual Store Store { get; set; }
        public virtual ICollection<Vat> Vat { get; set; }
    }
}
