//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klient.v03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Providers
    {
        public Providers()
        {
            this.Deliveries = new HashSet<Deliveries>();
            this.Deliveries1 = new HashSet<Deliveries>();
        }
    
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public string Adres { get; set; }
    
        public virtual ICollection<Deliveries> Deliveries { get; set; }
        public virtual ICollection<Deliveries> Deliveries1 { get; set; }
    }
}
