//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klient.v03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int ProduktId { get; set; }
        public int IloscDostepnych { get; set; }
        public int IloscZamowionych { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
