//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klient.v03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public int Produkt_id { get; set; }
        public int Ilosc_dostepnych { get; set; }
        public int Ilosc_zamowionych { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
