//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Klient.v03
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vat
    {
        public int Id { get; set; }
        public int Id_produktu { get; set; }
        public System.DateTime Od { get; set; }
        public Nullable<System.DateTime> Do { get; set; }
        public int Wartosc_vat { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
